const ADMIN_EMAIL = "piatrata@yandex.com";
const ADMIN_PASS = "1234";
let operators = JSON.parse(localStorage.getItem("operators") || "null") || [{id:1,name:"Serghei",password:"1111",active:true}];
let workers = JSON.parse(localStorage.getItem("workers") || "[]");
let advances = JSON.parse(localStorage.getItem("advances") || "[]");
let currentUser = JSON.parse(localStorage.getItem("currentUser") || "null");
let editingWorkerId = null;
function persist(){localStorage.setItem("operators",JSON.stringify(operators));localStorage.setItem("workers",JSON.stringify(workers));localStorage.setItem("advances",JSON.stringify(advances));}
function login(){const u=document.getElementById("loginUser").value.trim();const p=document.getElementById("loginPass").value.trim();if(u===ADMIN_EMAIL&&p===ADMIN_PASS){currentUser={name:"Administrator",role:"admin"};localStorage.setItem("currentUser",JSON.stringify(currentUser));render();return;}const op=operators.find(o=>o.name===u&&o.password===p&&o.active);if(op){currentUser={name:op.name,role:"operator",operatorId:op.id};localStorage.setItem("currentUser",JSON.stringify(currentUser));render();return;}alert("Utilizator sau parolă greșită");}
function logout(){localStorage.removeItem("currentUser");currentUser=null;render();}
function isAdmin(){return currentUser&&currentUser.role==="admin";}
function addOperator(){if(!isAdmin())return;const name=document.getElementById("opName").value.trim();const password=document.getElementById("opPass").value.trim();if(!name||!password){alert("Completează numele și parola operatorului");return;}if(operators.some(o=>o.name.toLowerCase()===name.toLowerCase())){alert("Acest operator există deja");return;}operators.push({id:Date.now(),name,password,active:true});document.getElementById("opName").value="";document.getElementById("opPass").value="";persist();render();}
function changeOpPass(id){const input=document.getElementById("pass_"+id);const pass=input.value.trim();if(!pass){alert("Scrie parola nouă");return;}operators=operators.map(o=>o.id===id?{...o,password:pass}:o);input.value="";persist();render();alert("Parola operatorului a fost schimbată");}
function toggleOperator(id){operators=operators.map(o=>o.id===id?{...o,active:!o.active}:o);persist();render();}
function saveWorker(){if(!isAdmin())return;const name=document.getElementById("wName").value.trim();const phone=document.getElementById("wPhone").value.trim();const salary=Number(document.getElementById("wSalary").value||0);const pin=document.getElementById("wPin").value.trim();if(!name){alert("Scrie numele muncitorului");return;}if(editingWorkerId){workers=workers.map(w=>w.id===editingWorkerId?{...w,name,phone,salary,pin}:w);}else{workers.push({id:Date.now(),name,phone,salary,pin,active:true,createdAt:new Date().toISOString()});}cancelEditWorker(false);persist();render();}
function editWorker(id){const w=workers.find(x=>x.id===id);if(!w)return;editingWorkerId=id;document.getElementById("wName").value=w.name;document.getElementById("wPhone").value=w.phone||"";document.getElementById("wSalary").value=w.salary||0;document.getElementById("wPin").value=w.pin||"";document.getElementById("workerBtn").innerText="Salvează modificările";document.getElementById("cancelWorkerBtn").classList.remove("hidden");window.scrollTo({top:0,behavior:"smooth"});}
function cancelEditWorker(doRender=true){editingWorkerId=null;["wName","wPhone","wSalary","wPin"].forEach(id=>document.getElementById(id).value="");document.getElementById("workerBtn").innerText="Adaugă muncitor";document.getElementById("cancelWorkerBtn").classList.add("hidden");if(doRender)render();}
function toggleWorker(id){workers=workers.map(w=>w.id===id?{...w,active:!w.active}:w);persist();render();}
function deleteWorker(id){if(!confirm("Ștergi muncitorul? Istoricul avansurilor rămâne salvat."))return;workers=workers.filter(w=>w.id!==id);persist();render();}
function nextCode(){const n=(Number(localStorage.getItem("advanceCounter")||0)+1);localStorage.setItem("advanceCounter",String(n));return "AV-"+String(n).padStart(6,"0");}
function addAdvance(){if(!currentUser)return;const workerId=Number(document.getElementById("workerSelect").value);const amount=Number(document.getElementById("advanceAmount").value||0);const pin=document.getElementById("advancePin").value.trim();const comment=document.getElementById("advanceComment").value.trim();const w=workers.find(x=>x.id===workerId&&x.active);if(!w){alert("Alege muncitorul");return;}if(!amount){alert("Scrie suma avansului");return;}if(w.pin&&pin!==w.pin){alert("PIN greșit");return;}advances.push({id:Date.now(),code:nextCode(),workerId,amount,comment,operator:currentUser.name,createdAt:new Date().toLocaleString("ro-RO")});document.getElementById("advanceAmount").value="";document.getElementById("advancePin").value="";document.getElementById("advanceComment").value="";persist();render();alert("Avans salvat");}
function totalForWorker(id){return advances.filter(a=>a.workerId===id).reduce((s,a)=>s+Number(a.amount||0),0);}
function render(){document.getElementById("login").classList.toggle("hidden",!!currentUser);document.getElementById("app").classList.toggle("hidden",!currentUser);if(!currentUser)return;document.getElementById("hello").innerText="Bun venit, "+currentUser.name;document.getElementById("role").innerText=isAdmin()?"Administrator":"Operator";["adminStats","adminOperators","adminWorkers","adminReport"].forEach(id=>document.getElementById(id).classList.toggle("hidden",!isAdmin()));const select=document.getElementById("workerSelect");select.innerHTML='<option value="">Alege muncitor</option>';workers.filter(w=>w.active).forEach(w=>select.innerHTML+=`<option value="${w.id}">${w.name}</option>`);if(isAdmin()){document.getElementById("stWorkers").innerText=workers.filter(w=>w.active).length;const totalAdv=advances.reduce((s,a)=>s+Number(a.amount||0),0);const totalSalary=workers.filter(w=>w.active).reduce((s,w)=>s+Number(w.salary||0),0);document.getElementById("stAdvances").innerText=totalAdv+" lei";document.getElementById("stRest").innerText=(totalSalary-totalAdv)+" lei";renderOperators();renderWorkersAdmin();renderReport();}renderAdvances();}
function renderOperators(){const tbody=document.getElementById("operatorsTable");tbody.innerHTML="";operators.forEach(o=>tbody.innerHTML+=`<tr><td>${o.name}</td><td>${o.active?"Activ":"Inactiv"}</td><td><input id="pass_${o.id}" placeholder="Parolă nouă"></td><td><button class="smallbtn" onclick="changeOpPass(${o.id})">Schimbă</button><button class="smallbtn ${o.active?'danger':'ok'}" onclick="toggleOperator(${o.id})">${o.active?'Dezactivează':'Activează'}</button></td></tr>`);}
function renderWorkersAdmin(){const tbody=document.getElementById("workersAdminTable");tbody.innerHTML="";workers.forEach(w=>tbody.innerHTML+=`<tr><td>${w.name}</td><td>${w.phone||""}</td><td>${w.salary||0}</td><td>${w.pin||""}</td><td>${w.active?"Activ":"Inactiv"}</td><td><button class="smallbtn" onclick="editWorker(${w.id})">Edit</button><button class="smallbtn ${w.active?'danger':'ok'}" onclick="toggleWorker(${w.id})">${w.active?'Dezactivează':'Activează'}</button><button class="smallbtn danger" onclick="deleteWorker(${w.id})">Șterge</button></td></tr>`);}
function renderReport(){const q=(document.getElementById("search")?.value||"").toLowerCase();const tbody=document.getElementById("reportTable");tbody.innerHTML="";workers.filter(w=>w.name.toLowerCase().includes(q)).forEach(w=>{const adv=totalForWorker(w.id);tbody.innerHTML+=`<tr><td>${w.name}</td><td>${w.phone||""}</td><td>${w.salary||0}</td><td>${adv}</td><td>${Number(w.salary||0)-adv}</td></tr>`});}
function renderAdvances(){const tbody=document.getElementById("advancesTable");tbody.innerHTML="";advances.slice().reverse().forEach(a=>{const w=workers.find(x=>x.id===a.workerId);tbody.innerHTML+=`<tr><td>${a.code}</td><td>${a.createdAt}</td><td>${w?w.name:"șters"}</td><td>${isAdmin()?a.amount+" lei":"Salvat"}</td><td>${a.operator}</td><td>${a.comment||""}</td></tr>`});}
function exportCSV(){let csv="Muncitor,Telefon,Salariu,Avansuri,Rest\n";workers.forEach(w=>{const adv=totalForWorker(w.id);csv+=`${w.name},${w.phone||""},${w.salary||0},${adv},${Number(w.salary||0)-adv}\n`;});const blob=new Blob([csv],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="brickstone_raport.csv";a.click();}
render();
